In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-pivoting-fail)

Here is a previously encountered matrix that factors well.

In [2]:
A = array([
    [2, 0, 4, 3],
    [-4, 5, -7, -10],
    [1, 15, 2, -4.5],
    [-2, 0, 2, -13]
    ])
L, U = FNC.lufact(A)
print(L)

[[ 1.   0.  -0.   0. ]
 [-2.   1.  -0.   0. ]
 [ 0.5  3.   1.   0. ]
 [-1.   0.  -2.   1. ]]


If we swap the second and fourth rows of $\mathbf{A}$, the result is still nonsingular. However, the factorization now fails.

In [3]:
A[[1, 3], :] = A[[3, 1], :]  
L, U = FNC.lufact(A)
print(L)

[[ 1.   nan  nan  0. ]
 [-1.   nan  nan  0. ]
 [ 0.5  inf  nan  0. ]
 [-2.   inf  nan  1. ]]


/Users/driscoll/Documents/GitHub/fnc/python/fncbook/fncbook/chapter02.py:47: RuntimeWarning: divide by zero encountered in divide
  L[:, k] = A_k[:, k] / U[k,k]
/Users/driscoll/Documents/GitHub/fnc/python/fncbook/fncbook/chapter02.py:47: RuntimeWarning: invalid value encountered in divide
  L[:, k] = A_k[:, k] / U[k,k]
/Users/driscoll/mambaforge/envs/myst/lib/python3.13/site-packages/numpy/_core/numeric.py:983: RuntimeWarning: invalid value encountered in multiply
  return multiply(a.ravel()[:, newaxis], b.ravel()[newaxis, :], out)


```{index} Python; NaN
```

The presence of `NaN` in the result indicates that some impossible operation was required. The source of the problem is easy to locate. We can find the first outer product in the factorization just fine:

In [4]:
U[0, :] = A[0, :]
L[:, 0] = A[:, 0] / U[0, 0]
A -= outer(L[:, 0],  U[0, :])
print(A)

[[  0.   0.   0.   0.]
 [  0.   0.   6. -10.]
 [  0.  15.   0.  -6.]
 [  0.   5.   1.  -4.]]


The next step is `U[1, :] = A[1, :]`, which is also OK. But then we are supposed to divide by `U[1, 1]`, which is zero. The algorithm cannot continue.