# Householder QR

We will use Householder reflections to produce a QR factorization of the matrix

In [1]:
A = rand(1.:9.,6,4)
m,n = size(A)

(6, 4)

Our first step is to introduce zeros below the diagonal in column 1. Define the vector

In [2]:
z = A[:,1];

Applying the Householder definitions gives us

In [3]:
using LinearAlgebra
v = z - norm(z)*[1;zeros(m-1)]
P = I - 2/(v'*v)*(v*v')   # reflector

6×6 Array{Float64,2}:
 0.295689   0.147844    0.221766    0.221766    0.591377   0.665299
 0.147844   0.968966   -0.0465517  -0.0465517  -0.124138  -0.139655
 0.221766  -0.0465517   0.930172   -0.0698275  -0.186207  -0.209483
 0.221766  -0.0465517  -0.0698275   0.930172   -0.186207  -0.209483
 0.591377  -0.124138   -0.186207   -0.186207    0.503449  -0.55862
 0.665299  -0.139655   -0.209483   -0.209483   -0.55862    0.371552

(Julia automatically fills in an identity of the correct size for the `I` above.) By design we can use the reflector to get the zero structure we seek:

In [4]:
P*z

6-element Array{Float64,1}:
 13.527749258468681
  4.440892098500626e-16
  4.440892098500626e-16
  4.440892098500626e-16
  8.881784197001252e-16
  1.7763568394002505e-15

Now we let

In [5]:
A = P*A

6×4 Array{Float64,2}:
 13.5277        9.31419    12.1972    13.8234
  6.38378e-16   0.674569    6.11896    4.14784
  3.88578e-16   0.0118532   4.67844    2.22177
  3.88578e-16   1.01185     0.678444   1.22177
  7.77156e-16  -1.30172     0.475851  -0.408623
  1.66533e-15   1.03556     3.03533   -0.334701

We are set to put zeros into column 2. We must not use row 1 in any way, lest it destroy the zeros we just introduced. To put it another way, we can repeat the process we just did on the smaller submatrix

In [6]:
A[2:m,2:n]

5×3 Array{Float64,2}:
  0.674569   6.11896    4.14784
  0.0118532  4.67844    2.22177
  1.01185    0.678444   1.22177
 -1.30172    0.475851  -0.408623
  1.03556    3.03533   -0.334701

In [7]:
z = A[2:m,2];
v = z - norm(z)*[1;zeros(m-2)];
P = I - 2/(v'*v)*(v*v');

We now apply the reflector to the submatrix.

In [8]:
A[2:m,2:n] = P*A[2:m,2:n]
A

6×4 Array{Float64,2}:
 13.5277        9.31419      12.1972   13.8234
  6.38378e-16   2.06056       3.58808   2.06056
  3.88578e-16  -3.23413e-18   4.70009   2.23962
  3.88578e-16  -1.52382e-16   2.52614   2.74561
  7.77156e-16   3.71222e-16  -1.90116  -2.36901
  1.66533e-15  -6.34236e-17   4.92632   1.22484

We need two more iterations of this process.

In [9]:
for j = 3:n
    z = A[j:m,j]
    v = z - norm(z)*[1;zeros(m-j)]
    P = I - 2/(v'*v)*(v*v')
    A[j:m,j:n] = P*A[j:m,j:n]
end

We have now reduced the original  to an upper triangular matrix using four orthogonal Householder reflections:

In [10]:
R = A

6×4 Array{Float64,2}:
 13.5277        9.31419      12.1972       13.8234
  6.38378e-16   2.06056       3.58808       2.06056
  3.88578e-16  -3.23413e-18   7.50701       3.72985
  3.88578e-16  -1.52382e-16  -3.15527e-16   2.39894
  7.77156e-16   3.71222e-16   3.5073e-16    2.88625e-16
  1.66533e-15  -6.34236e-17  -3.68968e-16   3.84193e-17