In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-svd-props)

We verify some of the fundamental SVD properties using standard Julia functions from `LinearAlgebra`.

In [2]:
A = array([[(i + 1.0) ** j for j in range(4)] for i in range(5)])
set_printoptions(precision=4)
print(A)

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]


```{index} ! Python; svd
```

The factorization is obtained using `svd` from `numpy.linalg`.

In [3]:
from numpy.linalg import svd
U, sigma, Vh = svd(A)
print("singular values:")
print(sigma)

singular values:
[1.4670e+02 5.7386e+00 9.9985e-01 1.1928e-01]


By default, the full factorization type is returned. This can be a memory hog if one of the dimensions of $\mathbf{A}$ is very large.

In [4]:
print("size of U:", U.shape)
print("size of V:", Vh.T.shape)

size of U: (5, 5)
size of V: (4, 4)


Both $\mathbf{U}$ and $\mathbf{V}$ are orthogonal (in the complex case, unitary). Note that it's $\mathbf{V}^*$ that is returned, not $\mathbf{V}$.

In [5]:
print(f"should be near zero: {norm(U.T @ U - eye(5), 2):.2e}")
print(f"should be near zero: {norm(Vh @ Vh.T - eye(4), 2):.2e}")

should be near zero: 5.61e-16
should be near zero: 1.07e-15


Next we test that we have the factorization promised by the SVD, using `diagsvd` to construct a rectangular diagonal matrix.

In [6]:
from scipy.linalg import diagsvd
S = diagsvd(sigma, 5, 4)
print(f"should be near zero: {norm(A - U @ S @ Vh, 2):.2e}")

should be near zero: 8.56e-14


Here is verification of the connections between the singular values, norm, and condition number.

In [7]:
from numpy.linalg import cond
print("largest singular value:", sigma[0])
print("2-norm of the matrix:  ", norm(A, 2))
print("singular value ratio:", sigma[0] / sigma[-1])
print("2-norm condition no.:", cond(A, 2))

largest singular value: 146.69715365883005
2-norm of the matrix:   146.69715365883005
singular value ratio: 1229.8468876337527
2-norm condition no.: 1229.8468876337529


For matrices that are much taller than they are wide, the thin SVD form is more memory-efficient, because $\mathbf{U}$ takes the same shape.

In [8]:
A = random.randn(1000, 10)
U, sigma, Vh = svd(A, full_matrices=False)
print("size of U:", U.shape)
print("size of V:", Vh.shape)

size of U: (1000, 10)
size of V: (10, 10)
