In [1]:
include("../../../julia/FNC_init.jl")

  Activating 

project at `~/Documents/GitHub/fnc`


[**Demo %s**](#demo-evd-eigen)


```{index} ! Julia; eigvals
```

The `eigvals` function returns a vector of the eigenvalues of a matrix.

In [2]:
A = π * ones(2, 2)

2×2 Matrix{Float64}:
 3.14159  3.14159
 3.14159  3.14159

In [3]:
λ = eigvals(A)

2-element Vector{Float64}:
 0.0
 6.283185307179586

```{index} ! Julia; eigen
```

If you want the eigenvectors as well, use `eigen`.

In [4]:
λ, V = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 0.0
 6.283185307179586
vectors:
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107

In [5]:
norm(A * V[:, 2] - λ[2] * V[:, 2])

0.0

```{index} ! Julia; sortby
```

Both functions allow you to sort the eigenvalues by specified criteria.

In [6]:
A = diagm(-2.3:1.7)
@show eigvals(A, sortby=real);
@show eigvals(A, sortby=abs);

eigvals(A, sortby = real) = [-2.3, -1.3, -0.3, 0.7, 1.7]


eigvals(A, sortby = abs) = 

[-0.3, 0.7, -1.3, 1.7, -2.3]


If the matrix is not diagonalizable, no message is given, but `V` will be singular. The robust way to detect that circumstance is via $\kappa(\mathbf{V})$.

```{index} condition number; of a matrix
```

In [7]:
A = [-1 1; 0 -1]
λ, V = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 -1.0
 -1.0
vectors:
2×2 Matrix{Float64}:
 1.0  -1.0
 0.0   2.22045e-16

In [8]:
cond(V)

9.007199254740991e15

Even in the nondiagonalizable case, $\mathbf{A}\mathbf{V} = \mathbf{V}\mathbf{D}$ holds.

In [9]:
opnorm(A * V - V * diagm(λ))

2.220446049250313e-16