In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-lu-outertri)

```{index} Python; tril, Python; triu
```
We explore the outer product formula for two random triangular matrices.

In [2]:
from numpy.random import randint
L = tril(randint(1, 10, size=(3, 3)))
print(L)

[[8 0 0]
 [8 6 0]
 [6 2 6]]


In [3]:
U = triu(randint(1, 10, size=(3, 3)))
print(U)

[[3 5 2]
 [0 5 2]
 [0 0 5]]


Here are the three outer products appearing in the sum in {eq}`matrixouter`:

In [4]:
print(outer(L[:, 0], U[0, :]))

[[24 40 16]
 [24 40 16]
 [18 30 12]]


In [5]:
print(outer(L[:, 1], U[1, :]))

[[ 0  0  0]
 [ 0 30 12]
 [ 0 10  4]]


In [6]:
print(outer(L[:, 2], U[2, :]))

[[ 0  0  0]
 [ 0  0  0]
 [ 0  0 30]]


Simply because of the triangular zero structures, only the first outer product contributes to the first row and first column of the entire product.