# Eigenvalue decomposition

In [1]:
using FundamentalsNumericalComputation

The `eigvals` function returns a vector of the eigenvalues of a matrix.

In [2]:
A = π*ones(2,2)

2×2 Matrix{Float64}:
 3.14159  3.14159
 3.14159  3.14159

In [3]:
λ = eigvals(A)

2-element Vector{Float64}:
 0.0
 6.283185307179586

If you want eigenvectors as well, use `eigen`.

In [4]:
λ,V = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 0.0
 6.283185307179586
vectors:
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107

In [5]:
norm( A*V[:,2] - λ[2]*V[:,2] )

0.0

If the matrix is not diagonalizable, no warning is given, but the columns of `V` corresponding to a repeated eigenvalue will not all be independent. That is, `V` will be singular.

In [6]:
A = [-1 1;0 -1]
λ,V = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
2-element Vector{Float64}:
 -1.0
 -1.0
vectors:
2×2 Matrix{Float64}:
 1.0  -1.0
 0.0   2.22045e-16

In [7]:
cond(V)

9.007199254740991e15

However, $\mathbf{A}\mathbf{V} = \mathbf{V}\mathbf{D}$ still holds.

In [8]:
opnorm(A*V - V*diagm(λ))

2.220446049250313e-16