In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-subspace-arnoldi)

We illustrate a few steps of the Arnoldi iteration for a small matrix.

In [2]:
A = random.choice(range(10), (6, 6))
print(A)

[[0 7 0 9 1 3]
 [8 0 9 5 4 9]
 [4 0 5 3 4 5]
 [5 7 0 9 2 1]
 [8 5 3 0 4 1]
 [2 3 1 2 0 1]]


The seed vector we choose here determines the first member of the orthonormal basis.

In [3]:
u = random.randn(6)
Q = zeros([6, 3])
Q[:, 0] = u / norm(u)

Multiplication by $\mathbf{A}$ gives us a new vector in $\mathcal{K}_2$.

In [4]:
Aq = A @ Q[:, 0]

We subtract off its projection in the previous direction. The remainder is rescaled to give us the next orthonormal column.

In [5]:
v = Aq - dot(Q[:, 0], Aq) * Q[:, 0]
Q[:, 1] = v / norm(v)

On the next pass, we have to subtract off the projections in two previous directions.

In [6]:
Aq = A @ Q[:, 1]
v = Aq - dot(Q[:, 0], Aq) * Q[:, 0] - dot(Q[:, 1], Aq) * Q[:, 1]
Q[:, 2] = v / norm(v)

At every step, $\mathbf{Q}_m$ is an ONC matrix.

In [7]:
print(f"should be near zero: {norm(Q.T @ Q - eye(3)):.2e}")

should be near zero: 4.20e-16


And $\mathbf{Q}_m$ spans the same space as the three-dimensional Krylov matrix.

In [8]:
from numpy.linalg import matrix_rank
K = stack([u, A @ u, A @ A @ u], axis=-1)
Q_and_K = hstack([Q, K])
print(matrix_rank(Q_and_K))

3
