In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-matrices-basics)

```{note}
While NumPy does have distinct representations for matrices and 2D arrays, use of the explicit matrix class is officially discouraged. We follow this advice here and use arrays to represent both matrices and vectors.
```

:::{index} ! Python; array, ! Python; shape
:::

<!-- :::{index}
see: Python; size, Python; shape
::: -->

A vector is created using square brackets and commas to enclose and separate its entries.

In [2]:
x = array([3, 3, 0, 1, 0 ])
print(x.shape)

(5,)


To construct a matrix, you nest the brackets to create a "vector of vectors". The inner vectors are the rows.

In [3]:
A = array([ 
    [1, 2, 3, 4, 5],
    [50, 40, 30, 20, 10], 
    [pi, sqrt(2), exp(1), (1+sqrt(5))/2, log(3)] 
    ])

print(A)
print(A.shape)

[[ 1.          2.          3.          4.          5.        ]
 [50.         40.         30.         20.         10.        ]
 [ 3.14159265  1.41421356  2.71828183  1.61803399  1.09861229]]
(3, 5)


In this text, we treat all vectors as equivalent to matrices with a single column. That isn't true in NumPy, because even an $n \times 1$ array has two dimensions, unlike a vector.

In [4]:
array([[3], [1], [2]]).shape

(3, 1)

:::{index} ! Python; hstack, ! Python; vstack
:::

You can concatenate arrays with compatible dimensions using `hstack` and `vstack`.

In [5]:
print( hstack([A, A]) )

[[ 1.          2.          3.          4.          5.          1.
   2.          3.          4.          5.        ]
 [50.         40.         30.         20.         10.         50.
  40.         30.         20.         10.        ]
 [ 3.14159265  1.41421356  2.71828183  1.61803399  1.09861229  3.14159265
   1.41421356  2.71828183  1.61803399  1.09861229]]


In [6]:
print( vstack([A, A]) )

[[ 1.          2.          3.          4.          5.        ]
 [50.         40.         30.         20.         10.        ]
 [ 3.14159265  1.41421356  2.71828183  1.61803399  1.09861229]
 [ 1.          2.          3.          4.          5.        ]
 [50.         40.         30.         20.         10.        ]
 [ 3.14159265  1.41421356  2.71828183  1.61803399  1.09861229]]


```{index} ! Python; transpose, ! Python; adjoint
```

Transposing a matrix is done by appending `.T` to it.

In [7]:
print(A.T)

[[ 1.         50.          3.14159265]
 [ 2.         40.          1.41421356]
 [ 3.         30.          2.71828183]
 [ 4.         20.          1.61803399]
 [ 5.         10.          1.09861229]]


For matrices with complex values, we usually want instead the adjoint or hermitian, which is `.conj().T`.

In [8]:
print((x + 1j).conj().T)

[3.-1.j 3.-1.j 0.-1.j 1.-1.j 0.-1.j]


:::{index} ! Python; arange, ! Python; linspace
:::

There are many convenient shorthand ways of building vectors and matrices other than entering all of their entries directly or in a loop. To get a vector with evenly spaced entries between two endpoints, you have two options.

In [9]:
print(arange(1, 7, 2))   # from 1 to 7 (not inclusive), step by 2        

[1 3 5]


In [10]:
print(linspace(-1, 1, 5))   # from -1 to 1 (inclusive), with 5 total values

[-1.  -0.5  0.   0.5  1. ]


The practical difference between these is whether you want to specify the step size in `arange` or the number of points in `linspace`.

Accessing an element is done by giving one (for a vector) or two index values in square brackets. **In Python, indexing always starts with zero, not 1.**

In [11]:
A = array([ 
    [1, 2, 3, 4, 5],
    [50, 40, 30, 20, 10], 
    linspace(-5, 5, 5) 
    ])
x = array([3, 2, 0, 1, -1 ])

In [12]:
print("row 2, col 3 of A:", A[1, 2])
print("first element of x:", x[0])

row 2, col 3 of A: 30.0
first element of x: 3


```{index} ! Python; slice, ! Python; \:
```
:::{index} ! Python; indexing arrays
:::

The indices can be ranges, in which case a **slice** or block of the matrix is accessed. You build these using a colon in the form `start:stop`. However, the last value of this range is `stop-1`, not `stop`.

In [13]:
print(A[1:3, 0:2])    # rows 2 and 3, cols 1 and 2

[[50.  40. ]
 [-5.  -2.5]]


If `start` or `stop` is omitted, the range extends to the first or last index.

In [14]:
print(x[1:])  # elements 2 through the end

[ 2  0  1 -1]


In [15]:
print(A[:2, 0])  # first two rows in column 1

[ 1. 50.]


Notice in the last case above that even when the slice is in the shape of a column vector, the result is just a vector with one dimension and neither row nor column shape.

There are more variations on the colon ranges. A negative value means to count from the end rather than the beginning. And a colon by itself means to include everything from the relevant dimension.

In [16]:
print(A[:-1, :])    # all rows up to the last, all columns

[[ 1.  2.  3.  4.  5.]
 [50. 40. 30. 20. 10.]]


Finally, `start:stop:step` means to step size or stride other than one. You can mix this with the other variations.

In [17]:
print(x[::2])  # all the odd indexes

[ 3  0 -1]


In [18]:
print(A[:, ::-1])  # reverse the columns

[[ 5.   4.   3.   2.   1. ]
 [10.  20.  30.  40.  50. ]
 [ 5.   2.5  0.  -2.5 -5. ]]


The matrix and vector senses of addition, subtraction, and scalar multiplication and division are all handled by the usual symbols. Two matrices of the same size (what NumPy calls shape) are operated on elementwise.

In [19]:
print(A - 2 * ones([3, 5]))  # subtract two from each element

[[-1.   0.   1.   2.   3. ]
 [48.  38.  28.  18.   8. ]
 [-7.  -4.5 -2.   0.5  3. ]]


```{index} ! Python; broadcast
```

If one operand has a smaller number of dimensions than the other, Python tries to **broadcast** it in the "missing" dimension(s), and the operation proceeds if the resulting shapes are identical.

In [20]:
print(A - 2)    # subtract two from each element

[[-1.   0.   1.   2.   3. ]
 [48.  38.  28.  18.   8. ]
 [-7.  -4.5 -2.   0.5  3. ]]


In [21]:
u = array([1, 2, 3, 4, 5])
print(A - u)    # repeat this row for every row of A

[[ 0.   0.   0.   0.   0. ]
 [49.  38.  27.  16.   5. ]
 [-6.  -4.5 -3.  -1.5  0. ]]


In [22]:
v = array([1, 2, 3])
print(A - v)  # broadcasting this would be 3x3, so it's an error

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [23]:
print(A - v.reshape([3, 1]))    # broadcasts to each column of A

[[ 0.   1.   2.   3.   4. ]
 [48.  38.  28.  18.   8. ]
 [-8.  -5.5 -3.  -0.5  2. ]]


```{index} ! Python; \@, ! Python; matmul
```

<!-- ```{index} 
see: Python; matrix multiplication, Python; \@
``` -->

```{index} ! Python; diag
```

Matrix–matrix and matrix–vector products are computed using `@` or `matmul`.

In [24]:
B = diag([-1, 0, -5])    # create a diagonal 3x3
print(B @ A)    # matrix product

[[ -1.   -2.   -3.   -4.   -5. ]
 [  0.    0.    0.    0.    0. ]
 [ 25.   12.5   0.  -12.5 -25. ]]


$AB$ is undefined for these matrix sizes.

In [25]:
print(A @ B)    # incompatible sizes

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

```{index} ! Python; elementwise multiplication, Python; broadcasting
```

The multiplication operator `*` is reserved for elementwise multiplication. Both operands have to be the same size, after any potential broadcasts.

In [26]:
print(B * A)    # not the same size, so it's an error

ValueError: operands could not be broadcast together with shapes (3,3) (3,5) 

In [27]:
print((A / 2) * A)    # elementwise

[[5.000e-01 2.000e+00 4.500e+00 8.000e+00 1.250e+01]
 [1.250e+03 8.000e+02 4.500e+02 2.000e+02 5.000e+01]
 [1.250e+01 3.125e+00 0.000e+00 3.125e+00 1.250e+01]]


To raise to a power elementwise, use a double star. This will broadcast as well.

In [28]:
print(B)
print(B**3)

[[-1  0  0]
 [ 0  0  0]
 [ 0  0 -5]]
[[  -1    0    0]
 [   0    0    0]
 [   0    0 -125]]


In [29]:
print(x)
print(2.0**x)

[ 3  2  0  1 -1]
[8.  4.  1.  2.  0.5]


```{danger}
If `A` is a matrix, `A**2` is *not* the same as mathematically raising it to the power 2.
```


```{index} Python; broadcasting
```

Most of the mathematical functions, such as cos, sin, log, exp and sqrt, expecting scalars as operands will be broadcast to arrays.

In [30]:
print(cos(pi * x))      

[-1.  1.  1. -1. -1.]
