In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-structure-cholesky)

A randomly chosen matrix is extremely unlikely to be symmetric. However, there is a simple way to symmetrize one.

In [2]:
A = 1.0 + floor(9 * random.rand(4, 4))
B = A + A.T
print(B)

[[18. 17.  6.  3.]
 [17. 14.  3. 11.]
 [ 6.  3. 12. 15.]
 [ 3. 11. 15. 14.]]


Similarly, a random symmetric matrix is unlikely to be positive definite. The Cholesky algorithm always detects a non-PD matrix by quitting with an error.

```{index} ! Python; cholesky
```

In [3]:
from numpy.linalg import cholesky
cholesky(B)    # raises an exception, not positive definite

LinAlgError: Matrix is not positive definite

It's not hard to manufacture an SPD matrix to try out the Cholesky factorization:

In [4]:
B = A.T @ A
R = cholesky(B)
print(R)

[[12.24744871  0.          0.          0.        ]
 [11.51260179  1.56843871  0.          0.        ]
 [ 5.87877538  2.7543314   8.82347202  0.        ]
 [ 9.06311205 -1.49192951  8.48070557  5.16834398]]


In [5]:
print(norm(R @ R.T - B) / norm(B))

5.1854534266302595e-17
