In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-qr-qrfact)


MATLAB provides access to both the thin and full forms of the QR factorization.

In [2]:
A = 1.0 + floor(9 * random.rand(6,4))
A.shape

(6, 4)

Here is the full form:

In [3]:
from numpy.linalg import qr
Q, R = qr(A, "complete")
print(f"size of Q is {Q.shape}")
print("R:")
print(R)

size of Q is (6, 6)
R:
[[-12.64911064 -10.2774024  -12.49099676 -11.22608569]
 [  0.          12.38446608   8.12509796   7.23688849]
 [  0.           0.           5.09487814  -2.36029745]
 [  0.           0.           0.          -4.36250398]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]


We can test that $\mathbf{Q}$ is an orthogonal matrix:

In [4]:
print(f"norm of (Q^T Q - I) is {norm(Q.T @ Q - eye(6)):.3e}")

norm of (Q^T Q - I) is 1.096e-15


The default for `qr`, and the one you usually want, is the thin form.

In [5]:
Q_hat, R_hat = qr(A)
print(f"size of Q_hat is {Q_hat.shape}")
print("R_hat:")
print(R_hat)

size of Q_hat is (6, 4)
R_hat:
[[-12.64911064 -10.2774024  -12.49099676 -11.22608569]
 [  0.          12.38446608   8.12509796   7.23688849]
 [  0.           0.           5.09487814  -2.36029745]
 [  0.           0.           0.          -4.36250398]]


Now $\hat{\mathbf{Q}}$ cannot be an orthogonal matrix, because it is not square, but it is still ONC. Mathematically, $\hat{\mathbf{Q}}^T \hat{\mathbf{Q}}$ is a $4\times 4$ identity matrix.

In [6]:
print(f"norm of (Q_hat^T Q_hat - I) is {norm(Q_hat.T @ Q_hat - eye(4)):.3e}")

norm of (Q_hat^T Q_hat - I) is 8.902e-16
