In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-structure-symm)

We begin with a symmetric $\mathbf{A}$.

In [2]:
A_1 = array([
    [2,     4,     4,     2],
    [4,     5,     8,    -5],
    [4,     8,     6,     2],
    [2,    -5,     2,   -26]
    ])

We won't use pivoting, so the pivot element is at position (1,1). This will become the first element on the diagonal of $\mathbf{D}$. Then we divide by that pivot to get the first column of $\mathbf{L}$.

In [3]:
L = eye(4)
d = zeros(4)
d[0] = A_1[0, 0]
L[:, 0] = A_1[:, 0] / d[0]
A_2 = A_1 - d[0] * outer(L[:, 0], L[:, 0])
print(A_2)

[[  0.   0.   0.   0.]
 [  0.  -3.   0.  -9.]
 [  0.   0.  -2.  -2.]
 [  0.  -9.  -2. -28.]]


We are now set up the same way for the submatrix in rows and columns 2–4.

In [4]:
d[1] = A_2[1, 1]
L[:, 1] = A_2[:, 1] / d[1]
A_3 = A_2 - d[1] * outer(L[:, 1], L[:, 1])
print(A_3)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -2. -2.]
 [ 0.  0. -2. -1.]]


We continue working our way down the diagonal.

In [5]:
d[2] = A_3[2, 2]
L[:, 2] = A_3[:, 2] / d[2]
A_4 = A_3 - d[2] * outer(L[:, 2], L[:, 2])
print(A_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]]


We have arrived at the desired factorization.

In [6]:
d[3] = A_4[3, 3]
print("diagonal of D:")
print(d)
print("L:")
print(L)

diagonal of D:
[ 2. -3. -2.  1.]
L:
[[ 1. -0. -0.  0.]
 [ 2.  1. -0.  0.]
 [ 2. -0.  1.  0.]
 [ 1.  3.  1.  1.]]


This should be comparable to machine roundoff:

In [7]:
print(norm(A_1 - (L @ diag(d) @ L.T), 2) / norm(A_1))

0.0
