In [4]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-evd-francisqr)

Let's start with a known set of eigenvalues and an orthogonal eigenvector basis.

In [5]:
from numpy.linalg import qr, eig
D = diag([-6, -1, 2, 4, 5])
V, R = qr(random.randn(5, 5))
A = V @ D @ V.T    # note that V.T = inv(V) here

In [6]:
print(sort(eig(A)[0]))

[-6. -1.  2.  4.  5.]


Now we will take the QR factorization and just reverse the factors.

In [7]:
Q, R = qr(A)
A = R @ Q;

It turns out that this is a similarity transformation, so the eigenvalues are unchanged.

In [8]:
print(sort(eig(A)[0]))

[-6. -1.  2.  4.  5.]


What's remarkable, and not elementary, is that if we repeat this transformation many times, the resulting matrix converges to $\mathbf{D}$.

In [9]:
for k in range(40):
    Q, R = qr(A)
    A = R @ Q
set_printoptions(precision=4)
print(A)

[[-6.0000e+00 -1.3117e-02  8.5915e-07 -7.7659e-16 -2.1476e-16]
 [-1.3117e-02  5.0000e+00 -1.4405e-04 -3.8313e-16  5.0982e-16]
 [ 8.5915e-07 -1.4405e-04  4.0000e+00  4.2644e-13 -7.9742e-16]
 [ 4.3764e-19 -7.6189e-18  4.2527e-13  2.0000e+00 -3.2831e-12]
 [-4.9283e-31 -7.8500e-30 -1.1727e-24 -3.2819e-12 -1.0000e+00]]
