In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-newtonsys-converge)

A system of nonlinear equations is defined by its residual and Jacobian.

In [2]:
def func(x):
    return array([
        exp(x[1] - x[0]) - 2, 
        x[0] * x[1] + x[2], 
        x[1] * x[2] + x[0]**2 - x[1]
    ])

def jac(x):
    return array([
            [-exp(x[1] - x[0]), exp(x[1] - x[0]), 0],
            [x[1], x[0], 1],
            [2 * x[0], x[2] - 1, x[1]],
    ])

Our initial guess at a root is the origin.

In [3]:
x1 = zeros(3)
x = FNC.newtonsys(func, jac, x1)
print(x)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.78586294e-01  1.57172588e-01  1.57172588e-01]
 [-4.63138615e-01  2.30903685e-01  1.15452497e-01]
 [-4.58026868e-01  2.35120714e-01  1.07713160e-01]
 [-4.58033281e-01  2.35113900e-01  1.07689991e-01]
 [-4.58033281e-01  2.35113900e-01  1.07689991e-01]]


The output has one row per iteration, so the last row contains the final Newton estimate. Let's compute its residual.

In [4]:
r = x[-1]
f = func(r)
print("final residual:", f)

final residual: [ 0.00000000e+00 -1.38777878e-17  0.00000000e+00]


Let's check the convergence rate:

In [5]:
logerr = [log(norm(x[k] - r)) for k in range(x.shape[0] - 1)]
for k in range(len(logerr) - 1):
    print(logerr[k+1] / logerr[k])

0.7937993447128695
3.6959808854483063
2.432659788997719
2.31109323743665
2.132541136303707


The ratio is apparently converging toward 2, as expected for quadratic convergence.