In [1]:
include("../../../julia/FNC_init.jl")

  Activating 

project at `~/Documents/GitHub/fnc`


[**Demo %s**](#demo-matrices-basics)

:::{index} ! Julia; size, ! Julia; length
:::

In Julia, vectors and matrices are one-dimensional and two-dimensional arrays, respectively. Square brackets are used to enclose elements of a matrix or vector. Use spaces for horizontal concatenation, and semicolons or new lines to indicate vertical concatenation.
```{tip}
:class: dropdown
The `size` function returns the number of rows and columns in a matrix. Use `length` to get the number of elements in a vector or matrix.
```

In [2]:
A = [ 1 2 3 4 5; 50 40 30 20 10
    π sqrt(2) exp(1) (1+sqrt(5))/2 log(3) ]

3×5 Matrix{Float64}:
  1.0       2.0       3.0       4.0       5.0
 50.0      40.0      30.0      20.0      10.0
  3.14159   1.41421   2.71828   1.61803   1.09861

In [3]:
m, n = size(A)

(3, 5)

A vector is not quite the same thing as a matrix: it has only one dimension, not two. Separate its elements by commas or semicolons:

In [4]:
x = [ 3, 3, 0, 1, 0 ]
size(x)

(5,)

For some purposes, however, an $n$-vector in Julia is treated like having a column shape. Note the difference if we use spaces instead of commas inside the brackets:

In [5]:
y = [ 3 3 0 1 0 ]
size(y)

(1, 5)

This $1\times 5$ matrix is not equivalent to a vector.

Concatenated elements within brackets may be matrices or vectors for a block representation, as long as all the block sizes are compatible.

In [6]:
[ x  x ]

5×2 Matrix{Int64}:
 3  3
 3  3
 0  0
 1  1
 0  0

In [7]:
[ x; x ]

10-element Vector{Int64}:
 3
 3
 0
 1
 0
 3
 3
 0
 1
 0

The `zeros` and `ones` functions construct matrices with entries all zero or one, respectively.

In [8]:
B = [ zeros(3, 2) ones(3, 1) ]

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  0.0  1.0
 0.0  0.0  1.0

```{index} ! Julia; transpose, ! Julia; adjoint, ! Julia; \'
```

A single quote `'` after a matrix returns its adjoint. For real matrices, this is the transpose; for complex-valued matrices, the elements are also conjugated.

In [9]:
A'

5×3 adjoint(::Matrix{Float64}) with eltype Float64:
 1.0  50.0  3.14159
 2.0  40.0  1.41421
 3.0  30.0  2.71828
 4.0  20.0  1.61803
 5.0  10.0  1.09861

If `x` is simply a vector, then its transpose has a row shape.

In [10]:
x'

1×5 adjoint(::Vector{Int64}) with eltype Int64:
 3  3  0  1  0

```{index} ! Julia; range, ! Julia; \:
```

There are many convenient shorthand ways of building vectors and matrices other than entering all of their entries directly or in a loop. To get a range with evenly spaced entries between two endpoints, you have two options. One is to use a colon `:`.

In [11]:
y = 1:4              # start:stop

1:4

In [12]:
z = 0:3:12           # start:step:stop

0:3:12

(Ranges are not strictly considered vectors, but they behave identically in most circumstances.) Instead of specifying the step size, you can give the number of points in the range if you use `range`.

In [13]:
s = range(-1, 1, 5)

-1.0:0.5:1.0

:::{index} ! Julia; end, ! Julia; indexing arrays
:::

Accessing an element is done by giving one (for a vector) or two (for a matrix) index values within square brackets. 
```{tip}
:class: dropdown
The `end` keyword refers to the last element in a dimension. It saves you from having to compute and store the size of the matrix first.
```
The matrix and vector senses of addition, subtraction, scalar multiplication, multiplication, and power are all handled by the usual symbols. 
:::{card}
Use `diagm` to construct a matrix by its diagonals. A more general syntax puts elements on super- or subdiagonals.
:::
::::

In [14]:
B = diagm( [-1, 0, -5] )   # create a diagonal matrix

3×3 Matrix{Int64}:
 -1  0   0
  0  0   0
  0  0  -5

In [15]:
@show size(A), size(B);
BA = B * A     # matrix product

(size(A), size(B)) = ((3, 5), (3, 3))

3×5 Matrix{Float64}:
  -1.0    -2.0       -3.0     -4.0      -5.0
   0.0     0.0        0.0      0.0       0.0
 -15.708  -7.07107  -13.5914  -8.09017  -5.49306

`A * B` causes an error here, because the dimensions aren't compatible.
```{tip}
:class: dropdown
Errors are formally called *exceptions* in Julia.
```

In [16]:
A * B    # throws an error

LoadError: DimensionMismatch: matrix A has axes (Base.OneTo(3),Base.OneTo(5)), matrix B has axes (Base.OneTo(3),Base.OneTo(3))

A square matrix raised to an integer power is the same as repeated matrix multiplication.

In [17]:
B^3    # same as B*B*B

3×3 Matrix{Int64}:
 -1  0     0
  0  0     0
  0  0  -125

Sometimes one instead wants to treat a matrix or vector as a mere array and simply apply a single operation to each element of it. For multiplication, division, and power, the corresponding operators start with a dot.

In [18]:
C = -A;

Because both matrices are $3\times 5$, `A * C` would be an error here, but elementwise operations are fine.

In [19]:
elementwise = A .* C

3×5 Matrix{Float64}:
    -1.0        -4.0    -9.0       -16.0       -25.0
 -2500.0     -1600.0  -900.0      -400.0      -100.0
    -9.8696     -2.0    -7.38906    -2.61803    -1.20695

```{index} Julia; broadcasting
```

The two operands of a dot operator have to have the same size—unless one is a scalar, in which case it is expanded or *broadcast* to be the same size as the other operand.

In [20]:
x_to_two = x .^ 2

5-element Vector{Int64}:
 9
 9
 0
 1
 0

In [21]:
two_to_x = 2 .^ x

5-element Vector{Int64}:
 8
 8
 1
 2
 1

Most of the mathematical functions, such as cos, sin, log, exp, and sqrt, expect scalars as operands. However, you can broadcast any function, including ones that you have defined, across a vector or array by using a special dot syntax.
```{tip}
:class: dropdown
A dot added to the end of a function name means to apply the function elementwise to an array.
```

In [22]:
show(cos.(π * x))    # broadcast to a function

[-1.0, -1.0, 1.0, -1.0, 1.0]

Rather than dotting multiple individual functions, you can use `@.` before an expression to broadcast everything within it.

In [23]:
show(@. cospi( (x + 1)^3) )    # broadcast an entire expression

[1.0, 1.0, -1.0, 1.0, -1.0]