In [1]:
include("../../../julia/FNC_init.jl")

  Activating 

project at `~/Documents/GitHub/fnc`


[**Demo %s**](#demo-structure-symm)


We begin with a symmetric $\mathbf{A}$.

In [2]:
A₁ = [  2     4     4     2
        4     5     8    -5
        4     8     6     2
        2    -5     2   -26 ];

We won't use pivoting, so the pivot element is at position (1,1). This will become the first element on the diagonal of $\mathbf{D}$. Then we divide by that pivot to get the first column of $\mathbf{L}$.

In [3]:
L = diagm(ones(4))
d = zeros(4)
d[1] = A₁[1, 1]
L[:, 1] = A₁[:, 1] / d[1]
A₂ = A₁ - d[1] * L[:, 1] * L[:, 1]'

4×4 Matrix{Float64}:
 0.0   0.0   0.0    0.0
 0.0  -3.0   0.0   -9.0
 0.0   0.0  -2.0   -2.0
 0.0  -9.0  -2.0  -28.0

We are now set up the same way for the submatrix in rows and columns 2–4.

In [4]:
d[2] = A₂[2, 2]
L[:, 2] = A₂[:, 2] / d[2]
A₃ = A₂ - d[2] * L[:, 2] * L[:, 2]'

4×4 Matrix{Float64}:
 0.0  0.0   0.0   0.0
 0.0  0.0   0.0   0.0
 0.0  0.0  -2.0  -2.0
 0.0  0.0  -2.0  -1.0

We continue working our way down the diagonal.

In [5]:
d[3] = A₃[3, 3]
L[:, 3] = A₃[:, 3] / d[3]
A₄ = A₃ - d[3] * L[:, 3] * L[:, 3]'
d[4] = A₄[4, 4]
@show d;
L

d = [2.0, -3.0, -2.0, 1.0]


4×4 Matrix{Float64}:
 1.0  -0.0  -0.0  0.0
 2.0   1.0  -0.0  0.0
 2.0  -0.0   1.0  0.0
 1.0   3.0   1.0  1.0

We have arrived at the desired factorization, which we can validate:

In [6]:
opnorm(A₁ - (L * diagm(d) * L'))

0.0