In [1]:
exec(open("../../../python/FNC_init.py").read())

[**Demo %s**](#demo-house-qr)


We will use Householder reflections to produce a QR factorization of a matrix.

In [2]:
A = 1.0 + floor(9 * random.rand(6,4))
m, n = A.shape
print(A)

[[7. 5. 2. 8.]
 [6. 1. 3. 6.]
 [1. 9. 8. 6.]
 [6. 2. 4. 3.]
 [5. 1. 5. 2.]
 [2. 6. 3. 8.]]


Our first step is to introduce zeros below the diagonal in column 1 by using {eq}`hhvector` and {eq}`hhreflect`.

In [3]:
z = A[:, 0]
v = z - norm(z) * hstack([1, zeros(m-1)])
P_1 = eye(m) - (2 / dot(v, v)) * outer(v, v)   # reflector

We check that this reflector introduces zeros as it should:

In [4]:
print(P_1 @ z)

[ 1.22882057e+01  6.66133815e-16  0.00000000e+00  6.66133815e-16
 -8.88178420e-16  1.11022302e-16]


Now we replace $\mathbf{A}$ by $\mathbf{P}_1\mathbf{A}$.

In [5]:
A = P_1 @ A
print(A)

[[ 1.22882057e+01  6.42892882e+00  7.73099036e+00  1.15557961e+01]
 [ 4.44089210e-16 -6.21263125e-01 -3.50238359e+00  1.96559253e+00]
 [ 0.00000000e+00  8.72978948e+00  6.91626940e+00  5.32759876e+00]
 [ 4.44089210e-16  3.78736875e-01 -2.50238359e+00 -1.03440747e+00]
 [-8.88178420e-16 -3.51052605e-01 -4.18652993e-01 -1.36200622e+00]
 [ 1.11022302e-16  5.45957896e+00  8.32538803e-01  6.65519751e+00]]


We are set to put zeros into column 2. We must not use row 1 in any way, lest it destroy the zeros we just introduced. So we leave it out of the next reflector.

In [6]:
z = A[1:, 1]
v = z - norm(z) * hstack([1, zeros(m-2)])
P_2 = eye(m-1) - (2 / dot(v, v)) * outer(v, v) 

We now apply this reflector to rows 2 and below only.

In [7]:
A[1:, 1:] = P_2 @ A[1:, 1:]
print(A)

[[ 1.22882057e+01  6.42892882e+00  7.73099036e+00  1.15557961e+01]
 [ 4.44089210e-16  1.03280625e+01  6.41921111e+00  7.91132021e+00]
 [ 0.00000000e+00 -1.19351358e-16 -9.94120360e-01  5.87128619e-01]
 [ 4.44089210e-16 -2.29786680e-17 -2.84557128e+00 -1.24007003e+00]
 [-8.88178420e-16  4.06604388e-17 -1.00551057e-01 -1.17137684e+00]
 [ 1.11022302e-16  0.00000000e+00 -4.11459052e+00  3.69052453e+00]]


We need to iterate the process for the last two columns.

In [8]:
for j in [2, 3]:
    z = A[j:, j]
    v = z - norm(z) * hstack([1, zeros(m-j-1)])
    P = eye(m-j) - (2 / dot(v, v)) * outer(v, v)
    A[j:, j:] = P @ A[j:, j:]

We have now reduced the original to an upper triangular matrix using four orthogonal Householder reflections:

```{index} Python; triu
```

In [9]:
R = triu(A)
print(R)

[[12.28820573  6.42892882  7.73099036 11.55579611]
 [ 0.         10.32806246  6.41921111  7.91132021]
 [ 0.          0.          5.10152103 -2.37618993]
 [ 0.          0.          0.          3.35086707]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
